default: &default
  flickr_key: test
  flickr_secret: test
  flickr_oauth_token: test
  flickr_oauth_secret: test
  sendgrid_username: test
  sendgrid_password: test

development:
  <<: *default
  secret_key_base: fae5f98711723330a8096db71d91396921d1a0bc73e9b97e8b6e8b440d07d88887f9b3ebf0ee889876748bd80bbb851fe405e5d0aa5d68a7c94b3c8543a20dd5

test:
  <<: *default
  secret_key_base: 6377b9ce93fb1fcc30341de519e61d75c2d2a1268556b345e5af18f4e5f5836fb0e113655922e1d8000c7662db6e8c3b243350e4ab123f34b316e565283ff7a5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  <<: *default
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  flickr_key: <%= ENV['FLICKR_KEY'] %>
  flickr_secret: <%= ENV['FLICKR_SECRET'] %>
  flickr_oauth_token: <%= ENV['FLICKR_OAUTH_TOKEN'] %>
  flickr_oauth_secret: <%= ENV['FLICKR_OAUTH_SECRET'] %>
